name: Monorepo PR Repo Labeler

on: [workflow_dispatch, pull_request]

jobs:
  labelPR:
    name: Label PR With Repo(s)
    runs-on: ubuntu-latest
    steps:
      - name: Label PRs
        uses: TinkurLab/monorepo-pr-labeler-action@4.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
